version: '3.8'
services:
  containermgmt-db:
    image: ghcr.io/epsindo-ai/containermgmt-postgres:16-alpine-v1.02-prod
    container_name: containermgmt-db
    ports:
      - 38432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: epsindo123
      POSTGRES_DB: containermgmt
    volumes:
      - ./data/postgres103:/var/lib/postgresql/data
    restart: always
  containermgmt-api:
    image: ghcr.io/epsindo-ai/container-mgmt-api:py3.10-dev
    container_name: containermgmt-api
    working_dir: /app
    ports:
     - 38800:8000
    environment:
      DB_HOST: containermgmt-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: epsindo123
      DB_NAME: containermgmt
      PARAMIKO_HOSTNAME: 172.23.1.62
      PARAMIKO_USERNAME: administrator
      PARAMIKO_PASSWORD: administrator
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./container-manager-api:/app
    depends_on:
      - containermgmt-db
    command:
      - "fastapi"
      - "run" 
      - "main.py"
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--reload"
    restart: always

  # containermgmt-watcher:
  #   image: ghcr.io/epsindo-ai/containermgmt-watcher:v1
  #   container_name: containermgmt-watcher
  #   command: ["python", "watcher.py"]
  #   volumes:
  #     - ./fullstack-watcher:/app
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - containermgmt-db
  
  dbgate:
    image: dbgate/dbgate:latest
    container_name: dbgate
    ports:
      - 38300:3000
    restart: always
