version: '3.8'

services:
  etcd:
    container_name: milvus-gpu-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - /home/ilham/milvus_database/volumes/etcd:/etcd
    ports:
      - "2399:2379"
    command: etcd --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - milvus-gpu

  minio:
    container_name: milvus-gpu-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9701:9001"
      - "9000:9000"
    volumes:
      - /home/ilham/milvus_database/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - milvus-gpu

  standalone:
    container_name: milvus-gpu-standalone
    image: milvusdb/milvus:v2.4.15-gpu
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      COMMON_STORAGETYPE: local
    volumes:
      - /home/ilham/milvus_database/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9093:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["2"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - etcd
      - minio
    restart: always
    networks:
      - milvus-gpu

  attu-gui:
    container_name: milvus-gpu-attu-gui
    image: zilliz/attu:v2.4.3
    environment:
      - MILVUS_URL=milvus-gpu-standalone:19530
    ports:
      - "19991:3000"
    depends_on:
      - standalone
    restart: always
    networks:
      - milvus-gpu

networks:
  milvus-gpu:
    name: milvus-gpu
    driver: bridge
